### ISSUE TITLE
get_obj_num must_be_small problem

### ISSUE THREAD

**Issue by techfan101** [HunterZ/umoria#4]
Hello All,

First, thank you for the great effort creating a repository for this classic game!   That said, I do note something unusual, which may or may not be an issue, in the get_obj_num function (in misc3.c).

In that function, must_be_small is used as one condition, for terminating a loop, but is never modified.   Is its purpose to limit the loop to a single iteration (when false)?   If so, no problem.   Its unclear, from the variable name, if this is the intent.

Apologies, if there was a better place in GitHub to ask questions about potential issues.   If this is the case, please let me know where I should do so.   I am brand new to this site.

Thank you,
-Eric.

**Comment by techfan101** [comment]
After puzzling over this for quite some time before posting, about two seconds after posting I figured it out.   Embarrassing...sorry for wasting anyone's time :(

**Comment by HunterZ** [comment]
No worries.

If I had a question I would probably post it at https://www.reddit.com/r/moriarl
