### ISSUE TITLE
really official?

### ISSUE THREAD

**Issue by dchmelik** [HunterZ/umoria#5]
Soooooooo... UMoria means Unix Moria, but you've renamed all source code archive files to only be non-Unix (or not for free POSIX-based OSes)--can you really call that ‘official?’

**Comment by HunterZ** [comment]
I never claimed anything to be official. David Grabiner is the official maintainer of UMoria, and as far as I know he hasn't officially passed the mantle to anyone. I just tried to capture the source versions that I was able to find, so that people could more easily find and work with them. I didn't change anything either, except on branches (not sure what your rename comment is referring to).

**Comment by dchmelik** [comment]
Okay... README.md text on your page says ‘official source code’...   What ‘source code archive file’ means is a .zip, .tar.gz, etc. containing source code, and I don't recall those named for Cygwin (which isn't for POSIX-based OSes like Unix or GNU/Linux, but Windows, so is actually a port of Unix Moria to Windows) but only recall the official file, moria-5.6.tar.gz that is actual Umoria or runs on similar POSIX-based OSes.  Maybe the Cygwin ones are also official then...?  Just, your Github repository doesn't have the Umoria file specifically for OS it was named for...

**Comment by HunterZ** [comment]
"Archive" has multiple meanings. My usage in the readme is referring to this GitHub project as a whole - like Internet Archive (archive.org) or The Interactive Fiction Archive (ifarchive.org) - and does not refer to an archive *file*.

The master branch of the Git repo contains the source code history for official releases 4.8.7 through 5.6 (all versions of UMoria that I was able to locate source code for at the time), while other branches contain the source code of unofficial modest 5.6 Windows port efforts by myself.

If you want an archive *file* containing any of the official source releases, you can get them on the tags page: https://github.com/HunterZ/umoria/tags

Note that everything after 5.6 is just my unofficial Windows ports based on 5.6 (hence the dash followed by compiler and release number).

**Comment by dchmelik** [comment]
I forgot what this was about.  Maybe Github just renamed the .tar.gz to .zip.  The official maintainer hasn't trademarked Moria (I guess that would be an issue with the Tolkien estate) but it still could be confusing calling something official, but apparently not a big deal.  I'll just close this.  Interesting to see what updates you are and will be making.
