### ISSUE TITLE
free-moria.sourceforge.net source code link broken

### ISSUE THREAD

**Issue by dchmelik** [HunterZ/umoria#8]
Your [http://free-moria.sourceforge.net/](http://free-moria.sourceforge.net/) source code link is broken, with some stuff before the URL: can you please check/fix the page's HTML?

**Comment by HunterZ** [comment]
I didn't even know I had access to do that, but it looks like Ben Asselstine added me as a project admin.

Anyway, it should be fixed now - can you confirm?

**Comment by dchmelik** [comment]
I don't really know what that means, but yes.  Now that Dr David Grabiner's homepage/homesite has been down a few years, is that Free Moria website considered (by him) an official website for the game?  I know the C++ fork isn't official (though he isn't against it, introduced some new bugs).  I maintain [moria SlackBuild](http://slackbuilds.org/repository/15.0/games/moria/) and it needs an official website.

**Comment by HunterZ** [comment]
Thanks, I'll mark this issue as closed.

Ben Asselstine was really the driving force behind the free-moria project, while I ended up mostly providing moral support. He also did all the work setting up and maintaining the Sourceforge page/project, so I didn't know/remember that I even had access to update it.

Interesting to know that folks are still building the original source, and that David's site is gone.
